apiVersion: v1
kind: Secret
metadata:
  name: chaos-stream-secrets
  namespace: chaos-stream
type: Opaque
data:
  postgres-user: dXNlcg==       # "user"
  postgres-password: cGFzc3dvcmQ=  # "password"
