server:
  port: ${AUTH_SERVICE_PORT:9000}
spring:
  application:
    name: auth-service
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.95,0.99
